name: Check the source code
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Setup node.js 14.x
        - uses : actions/setup-node@v3
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
