name: Check the source code
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        width:
          node-version: 14.x

      - name: install dependencies
        run: yarn install

      - name: run eslint
        run: npm run lint
